### ISSUE TITLE
Published package contains large test files

### ISSUE THREAD

**Issue by daniellockyer** [medikoo/punycode2#1]
Hey @medikoo! 👋🏻 

I was just browsing the dependencies of [Ghost](https://github.com/tryghost/ghost) to see where we can trim down. It seems `punycode2` is one of our largest packages. Looking into the NPM package, it contains the `test/` directory, which has a 17.7MB file.

Would it be possible to add this to an .npmignore file and publish a new version?

Thanks! 🙂 

(also happy to do it myself if you can give me GitHub and NPM permissions)

**Comment by medikoo** [comment]
@daniellockyer great thanks for that request. I'll try to tackle that this week.

**Comment by medikoo** [comment]
Published with v1.0.1

**Comment by daniellockyer** [comment]
Thanks!
